### ISSUE TITLE
decodeURI error with gbk

### ISSUE THREAD

**Issue by lovelywcm** [iamamac/autoproxy2pac#13]
`http:*.google.*search*½ (|http:*.google.*search*%D5%C5%B5%C2%BD%AD)`

should be:

`http:*.google.*search*张德江 (|http...)`

It would be better to catch exception from decode('utf-8') and try it again with decode('gbk', 'ignore').

I have sent a pull request.

**Comment by iamamac** [comment]
Fixed, thanks
