### ISSUE TITLE
google search is not always work for firefox

### ISSUE THREAD

**Issue by bash99** [iamamac/autoproxy2pac#14]
search 谭作人 from search toolbox，the url is
http://www.google.com/search?q=谭作人&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:zh-CN:official&client=firefox

but autoproxy2pac only match
http://www.google.com/search?q=%E8%B0%AD%E4%BD%9C%E4%BA%BA

perhaps I should use autoproxy when use firefox?

**Comment by iamamac** [comment]
It's an encoding bug in gfwlist: AutoProxy will suffer too. Anyway, it has been fixed.
