### ISSUE TITLE
RSS & JSON: Ignore unmodified rules

### ISSUE THREAD

**Issue by lovelywcm** [iamamac/autoproxy2pac#9]
for example:

1月13日 gfwlist 更新: 增加 5 条, 删除 6 条
2010年01月13日 10:06
解封网址
    \* .amoiist.com
    \* ||amoiist.com
    \* ||www.earthhour.org
    \* ||blog.gatein.or
    \* ||http://blog.nihilogic.dk
    \* ||http://rss.slashdot.org

封锁网址
    \* .amoiist.com
    \* ||amoiist.com
    \* ||blog.gatein.org
    \* ||blog.nihilogic.dk
    \* ||rss.slashdot.org

"amoiist.com" is totally unmodified (though moved from a catalog to another), better to ignore it.

**Comment by iamamac** [comment]
Fixed. Will ignore duplicate rules in the future, but the past will not change until a database rebuild.
